<Project Sdk="Aspire.AppHost.Sdk/13.3.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="13.3.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PoC.Pulsar.TableView.Cli\PoC.Pulsar.TableView.Cli.csproj" />
    <ProjectReference Include="..\PoC.Pulsar.TableView.Processor\PoC.Pulsar.TableView.Processor.csproj" />
  </ItemGroup>

</Project>
