{
  "type": "record",
  "name": "RawCategoryMessage",
  "namespace": "PoC.Pulsar.TableView.Contracts",
  "fields": [
    { "name": "Id", "type": "string" },
    { "name": "Provider", "type": "string" },
    { "name": "EntityCoverage", "type": "string" },
    {
      "name": "ExternalEntities",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "ExternalEntity",
          "fields": [
            { "name": "Id", "type": "string" },
            { "name": "Provider", "type": "string" },
            { "name": "EntityCoverage", "type": "string" },
            { "name": "DefaultName", "type": "string" }
          ]
        }
      },
      "default": []
    },
    { "name": "Name", "type": "string" },
    { "name": "SportId", "type": "string" },
    { "name": "ParentId", "type": ["null", "string"], "default": null },
    { "name": "SportType", "type": ["null", "string"], "default": null },
    { "name": "CountryCode", "type": ["null", "string"], "default": null },
    { "name": "Gender", "type": ["null", "string"], "default": null }
  ]
}
